config/routes.rb
ProcializeApp::Application.routes.draw do

  resources :noir_quizzes

  get "exhibitor/index"

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  match 'linkedin_desktop',:to => "desktop_view#linkedin_desktop" ,:as => "linkedin_desktop"

  get "desktop_view/index"

  get "ratings/index"

  get "speaker/index"

  get "moderator/moderator_view"

  get "moderator_view/moderator"

  match '/update_artists/:event_day_id', :to => "events#update_artists"#, :as => "update_artists"
  match '/update_songs/:event_id', :to => "events#update_songs"#, :as => "update_songs"
  match 'desktop_view/update_track/:event_day_id', :to => "desktop_view#update_track"#, :as => "update_track"
  match 'desktop_view/update_event/(:event_id)', :to => "desktop_view#update_event" #, :as => "update_event"

  resources :invitees
  resources :user_imports
  match '/excel_imp', :to => "user_imports#excel_imp" , :as => "excel_imp"

  resources :exhibitor_imports
  match '/exhibitor_excel_imp', :to => "exhibitor_imports#exhibitor_excel_imp" , :as => "exhibitor_excel_imp"

  resources :exhibitor_user_imports
  match '/exhibitor_user_excel_imp', :to => "exhibitor_user_imports#exhibitor_user_excel_imp" , :as => "exhibitor_user_excel_imp"

  mount RailsAdmin::Engine => '/organizer', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  resources :meetings
  resources :messages
  resources :events do
    resources :questionables
  end
  resources :contacts

  match 'users/:id/profile', :to => "users/profile#index", :as => "user_profile"
  match 'users/:id/profile/edit', :to => "users/profile#edit", :as => "edit_user_profile"
  match 'users/:id/follow', :to => "users/profile#following", :as => "follow"
  match '/update_status', :to => "home#update_status", :as => "update_status"

  match '/messages/focus/new/:id/(:message)/(:all)', :to => "messages#focussed_new", :as => "focussed_message"

  match '/meetings/focus/new/:id', :to => "meetings#focussed_new", :as => "focussed_meeting"

  match '/meeting_new_user', :to => "meetings#meeting_new_user", :as => "meeting_new_user"
  match '/message_new_user', :to => "messages#message_new_user", :as => "message_new_user"

  match '/show_page/event/:id', :to => 'events#show_page', :as => "show_track"
  match '/track_page/event/:id', :to => 'events#track_page', :as => "event_track"

  match '/followers_status', :to => "home#followers_status", :as => "followers_status"
  match '/accept/event/:id', :to => "events#accept", :as => "attend_event"
  match '/accept/meeting/:id', :to => "meetings#accept", :as => "accept_meeting"
  match '/decline/meeting/:id', :to => "meetings#decline", :as => "decline_meeting"
  match '/update_location', :to => "application#update_location", :as => "update_location"
  get 'search/search'
  match 'users/:id/edit', :to => "users/profile#edit", :as => "edit"
  match 'users/:id/update', :to => "users/profile#update", :as => "update"
  match '/messages/:id', :to => "messages#show"
  match '/create_question', :to => "questionables#create_question",:as => "create_question"
  match '/hide_quest', :to => "questionables#hide_quest", :as => "hide_quest"
  match '/approve_quest', :to => "questionables#approve_quest", :as => "approve_quest"
  match '/questionables/index/(:id)', :to => "questionables#index"
  match '/unapproved_view', :to => "questionables#unapproved_view"
  match '/print/(:id)', :to => "questionables#print"
  match '/graffiti', :to => "home#graffiti"
  match '/speaker', :to => "speaker#index"
  match '/ask_question', :to => "questionables#ask_question", :as => "ask_question"
  match '/ratings', :to => "ratings#index"
  match '/user_event', :to => "ratings#user_event", :as => "user_event"
  match '/rating_up', :to => "ratings#rating_up", :as => "rating_up"
  match "/send_mailers", :to => "invitees#send_mailers", :as => "send_mailers"
  match "/send_mailers_recommend", :to => "invitees#send_mailers_recommend", :as => "send_mailers_recommend" #---------for desktop------------#
  match "/search_delegates", :to => "search#search_delegates"
  match "/logos", :to => "application#logos", :as => "logos"
  match "/create_quest", :to => "events#create_quest", :as => "create_quest"

  match '/themes', :to => "home#theme_changer", :as => "themes"
  match '/users/auth/:provider/callback' => 'users/omniauth_callbacks#facebook'
  match '/voting' => "questionables#voting", :as => "voting"
  match '/concierge_service' => "home#concierge_service", :as => 'concierge_service'
  match '/order_services/:message' => "home#order_services", :as => 'order_services'
  match '/recommendation' => "home#recommendation", :as => 'recommendation'
  match '/gettweets', :to => "home#gettweets"
  match '/settweetcounter/:count', :to => "home#settweetcounter"
  match '/assets_download', :to => "home#assets_download", :as => "assets_download"
  match '/update_assets', :to => "home#update_assets", :as => "update_assets"

  match '/send_mail_to_recommended_users', :to => "home#send_mail_to_recommended_users", :as => "send_mail_to_recommended_users"
  match '/survey', :to => "home#survey"
  match '/survey_storing', :to => "home#survey_storing", :as => "survey_storing"

  match '/editing_profile', :to => "home#editing_profile", :as => "editing_profile"
  match '/editing_profile_location', :to => "home#editing_profile_location", :as => "editing_profile_location"
  match '/editing_profile_skills', :to => "home#editing_profile_skills", :as => "editing_profile_skills"
  match '/editing_profile_interest', :to => "home#editing_profile_interest", :as => "editing_profile_interest"

  match '/questions_appending/:track_id', :to => "questionables#questions_appending", :as => "questions_appending"
  match '/questions_finding', :to => "questionables#questions_finding", :as => "questions_finding"

  match '/rating_appending', :to => "ratings#rating_appending", :as => "rating_appending"
  match '/complete', :to => "meetings#complete", :as => "complete"
  match '/complete', :to => "meetings#complete", :as => "complete"

  match '/index', :to => "exhibitor#index", :as => "exhibitor"
  match '/:id/exhibitor', :to => "exhibitor#show" ,:as => "exhibitor_profile"

  match '/noir_case', :to => "noir_quizzes#noir_case", :as => "noir_case"

  resources :desktop_view

  match '/desktop_events', :to => 'desktop_view#desktop_events', :as => "desktop_events"
  match '/events_show/:id', :to => "desktop_view#events_show", :as => "events_show"
  match '/desktop_create_quest', :to => "desktop_view#desktop_create_quest", :as => "desktop_create_quest"
  match '/desktop_accept/event/:id', :to => "desktop_view#desktop_accept", :as => "desktop_accept"

  match '/feed_me', :to => "desktop_view#feed_me", :as => "feed_me"
  match '/desktop_ratings', :to => "desktop_view#desktop_ratings", :as => "desktop_ratings"
  match '/desktop_rating_appending', :to => "desktop_view#desktop_rating_appending", :as => "desktop_rating_appending"

  match '/meetings_index', :to => 'desktop_view#meetings_index', :as => "meetings_index"
  match '/desktop_focussed_new/:id', :to => "desktop_view#desktop_focussed_new", :as => "desktop_focussed_meeting"
  match '/meetings_new', :to => "desktop_view#meetings_new"
  match '/meetings_create', :to => "desktop_view#meetings_create", :as => "meetings_create"
  match '/meetings_show/:id', :to => "desktop_view#meetings_show", :as => "meetings_show"
  match '/meetings_accept/meeting/:id', :to => "desktop_view#meetings_accept", :as => "meetings_accept"
  match '/meetings_edit/:id', :to => "desktop_view#meetings_edit"
  match '/desktop_meeting_new_user', :to => "desktop_view#desktop_meeting_new_user", :as => "desktop_meeting_new_user"

  match '/messages_index', :to => 'desktop_view#messages_index', :as => "messages_index"
  match '/desktop_message_focussed_new/:id/(:message)/(:all)', :to => "desktop_view#desktop_message_focussed_new", :as => "desktop_focussed_message"
  match '/messages_new', :to => "desktop_view#messages_new", :as => "messages_new"
  match '/messages_create', :to => "desktop_view#messages_create", :as => "messages_create"
  match '/messages_show/:id', :to => "desktop_view#messages_show", :as => "messages_show"
  match '/messages_edit/:id', :to => "desktop_view#messages_edit"
  match '/messages_accept/meeting/:id', :to => "desktop_view#messages_accept", :as => "messages_accept"

  match '/delegates_search', :to => "desktop_view#delegates_search", :as => "delegates_search"
  match ':id/delegate_profile_index', :to => "desktop_view#delegate_profile_index", :as => "delegate_profile_index"
  match ':id/follow', :to => "desktop_view#desktop_following", :as => "desktop_following"
  match '/:id/desktop_edit_profile', :to => "desktop_view#desktop_edit_profile", :as => "desktop_edit_profile"
  match '/:id/desktop_update_profile', :to => "desktop_view#desktop_update_profile", :as => "desktop_update_profile"

  match '/desktop_graffiti', :to => "desktop_view#desktop_graffiti", :as => "desktop_graffiti"

  match '/desktop_assets_download', :to => "desktop_view#desktop_assets_download", :as => 'desktop_assets_download'

  match '/desktop_speaker', :to => "desktop_view#desktop_speaker", :as => 'desktop_speaker'

  match '/concierge_service_desktop', :to => "desktop_view#concierge_service_desktop", :as => "concierge_service_desktop"
  match '/order_services_desktop/:message', :to => "desktop_view#order_services_desktop", :as => "order_services_desktop"

``#----------Contact Us-------------#
  match '/contact_us_new', :to => "desktop_view#contact_us_new", :as => "contact_us_new"
  match '/contact_us_create', :to => "desktop_view#contact_us_create", :as => "contact_us_create"

``#----------Questionables-------------#
  match '/desktop_ask_question', :to => "desktop_view#desktop_ask_question", :as => "desktop_ask_question"

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :end_time, :location, :name, :start_time ,:user_id,:event_day_id

  has_many :meeters, :dependent => :destroy
  has_many :users, :through => :meeters
  #accepts_nested_attributes_for :meeters, :reject_if => proc { |attrs| reject = %w(user_id).all? { |a| attrs[a].blank? } }, :allow_destroy => true


  belongs_to :event_day
  belongs_to :user

end

app/controllers/meeting_controller.rb
class MeetingController < ApplicationController

  def index
     @user=current_user
     @meetings = Meeting.all
     #@meetings = Meeting.find(params[:id])
     @meeters = Meeter.find_all_by_user_id(@user)
     @meetings =Array.new
     @meeters.each do |meeters|
       @meetings<<Meeting.find(meeters.meeting_id)
     end


  end

   def show
     #@meetings = Meeting.find(params[:id])
   end

 
  def new

  end

  def new_resp

  end

  def show_resp

  end

  
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index

    @meetings = Meeting.all
    @user = current_user
    @pending = Meeter.find_all_by_user_id_and_status(current_user.id, nil).map { |r| r.meeting }
    @scheduled = Meeter.find_all_by_user_id_and_status(current_user.id, true).map { |r| r.meeting }
    @declined = Meeter.find_all_by_user_id_and_status(current_user.id, false).map { |r| r.meeting }
    @sent = Meeting.find_all_by_user_id(@user.id).last(10).reverse
    @open=[]

    @sent.each do |meeting|
      #if meeting.meeters.select{|meeter| meeter.status}.length==meeting.meeters.length
      if meeting.meeters.select{|meeter| meeter.status}.length>=1
        @scheduled << meeting
      else
        @open<<meeting
      end
    end

    @scheduled.flatten
    @open.flatten


    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @meetings }
    #end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])
    @meeter = Meeter.find_by_user_id_and_meeting_id(current_user.id, @meeting.id)

    render :layout => 'meeting_show'
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new
    @users=[]
    @followed=Follower.find_all_by_user_id(current_user.id).map { |f| User.find(f.follower_id) }
    @users<<@followed
    @users<<(User.all - @followed)
    @user_list=@users.flatten.map {|u| [u.name, u.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @meeting }
    end
  end

  # GET /meetings/focussed/new
  def focussed_new
    @meeting = Meeting.new
    @meeter = params[:id]
    @users=[]
    @followed=Follower.find_all_by_user_id(current_user.id).map { |f| User.find(f.follower_id) }
    @users<<@followed
    @users<<(User.all - @followed)
    @user_list=@users.flatten.map {|u| [u.name, u.id]}
    respond_to do |format|
      format.html # focussed_new.html.erb
      format.json { render :json => @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  #def meeting_new_user
  #  @me=Mezeter.create!(:user_id => params[:meeter_users][0])
  #end



  def create
    params[:meeting].parse_time_select! :start_time
    @meeting = Meeting.new(params[:meeting])
    respond_to do |format|
      if @meeting.save
        params[:meeter_use].each do |uid|
         Meeter.create!(:meeting_id => @meeting.id, :user_id =>uid )
         @invitee=Invitee.create!(:name=>User.find(uid).name, :email=>User.find(uid).email)
          UserMailer.meeting_confirmation(@invitee).deliver
       end
        format.html { redirect_to meetings_path, :notice => 'Meeting was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :action => "new" }
        format.json { render :json => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])
    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, :notice => 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to meetings_path
    #respond_to do |format|
    #  format.html { redirect_to meetings_url }
    #  format.json { head :no_content }
    #end
  end

  def accept
    @meeting=Meeting.find(params[:id])
    @meeter=@meeting.meeters.where('user_id=?',current_user.id).first
    @meeter.status=true
    @meeter.save
    redirect_to meetings_path
  end

  def decline
    @meeting=Meeting.find(params[:id])
    @meeter=@meeting.meeters.where('user_id=?',current_user.id).first
    @meeter.status=false
    @meeter.save
    redirect_to meetings_path
  end

  def search
    @meeting = Meeting.new
    @meeter = params[:id]
    @users=[]
    @followed=Follower.find_all_by_user_id(current_user.id).map { |f| User.find(f.follower_id) }
    @users<<@followed
    @users<<(User.all - @followed)
    @user_list=@users.flatten.map {|u| [u.name, u.id]}
    #@user_list.search params[:teacher][:search_by],params[:teacher][:search]

  end



end

app/helpers/meeting_helper.rb
module MeetingHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/focussed_new.html.erb
<%= content_for :page_title do %>
    New Meetings
<% end %>



<%= content_for :head do %>
    <script type="text/javascript">

        $(function(){

            $('[type="submit"]').button('disable');
            $(function () {
                $('[type="submit"]').button('disable');
                $('select').change && $('#meeting_name').focus (function () {
                    if (($('select option:selected') && $('#meeting_name')).length > 0) {
                        $('[type="submit"]').button('enable');

                    } else {
                        $('[type="submit"]').button('disable');

                    }
                });

            });

            $('#meeting_name').blur(function () {
                if ($(this).val().length <= 0) {
                    $('[type="submit"]').button('disable');
                }
                else{
                    $('[type="submit"]').button('enable');
                }
            });

        }) ;





    </script>
<% end %>





<%= content_for :page_menu do %>

<% end %>


<%= form_for :meeting, :url => {:action => :create},:html => {:class => "meeting",:id=> "meeting_form", :'data-ajax'=>"false"} do |f| %>

    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="field">
      <%= f.text_field :name, :'data-mini' => true, :placeholder => "Enter meeting agenda" %>
    </div>
      <br>
    <div data-role="listview" data-mini="true"  data-placeholder="true"  data-split-icon='star' data-mini="true" data-filter="true">
      <%= select_tag 'meeter_use[]', options_for_select(@users.flatten.map {|u| [u.name, u.id]}, @meeter), :multiple => true,:include_blank =>"Select Delegates", :multiple => true,:'data-mini' => true,:prompt => "Select Delegates" %>
    </div>
     <br>
    <div class="field">
      <%= f.select :location, options_for_select(@conference.locations.map { |l| [l.name, l.id] }), :'data-mini' => true,:prompt => "Select Location" %>
    </div>
    <br>
    <div class="field">
      <%= f.time_select :start_time,
                        :combined => true,
                        #:default => Time.now.change(:hour => 11, :min => 30),
                        :minute_interval => 30,
                        :time_separator => "",
                        :start_hour => 00,
                        :end_hour => 23,:prompt => "Select Time" %>
    </div>
     <br>






    <div data-role="controlgroup" data-type="horizontal" style="float: right;">
      <a class="index_styling" href="#" data-ajax=false data-role="button" class="form_btn" id="form_btn_id" data-mini="true">Send</a>
      <%#= f.submit "Send", :'data-role' => "button"%>
    </div>

<% end %>


<script type="text/javascript">
    $('#form_btn_id').click(function(){
        if ($("#meeting_start_time_5i").val()==""){
        <%= add_gritter("Please select Time", :title => "Error!",:image => :warning,:time => 2000  ) %>
        }
        else if ($("#meeting_location").val()==""){
        <%= add_gritter("Please select Location", :title => "Error!",:image => :warning,:time => 2000  ) %>
        }
        else if ($('#meeting_name').val()==""){
        <%= add_gritter("Please fill meeting Agenda", :title => "Error!",:image => :warning,:time => 2000  ) %>
        }
        else
        {
            $('#meeting_form').submit();
        }
    });

</script>

app/views/meetings/index.html.erb
<%= content_for :page_title do %>
    Meetings
<% end %>


<%= link_to "Create New",new_meeting_path,:'data-role' => "button", :'data-theme' => "a", :'data-ajax' => false, :'data-inline' => true, :class => "anchor_link",:'data-mini' => "true",:style=>"float:right;" %>
<br>
<br>
<br>

<div data-role="collapsible" data-theme="a" data-collapsed="true" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d" data-inset="false" data-mini="true">
  <h3 style="font-size: 0.8em;">Scheduled Meetings&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @scheduled.size %></h3>
  <ul data-role="listview" data-theme="a" data-divider-theme="d">
    <% @scheduled.each do |meeting| %>
        <li>
          <a href="<%= meeting_path(meeting) %>" data-ajax="false">
            <h3 style="font-size: 0.8em;"><%= meeting.start_time %> hrs on <%= meeting.start_time.strftime("%d %b") %></h3>
            <p><b><%= ((meeting.meeters.select{|m| m.status}.map{|m| m.user.name} << meeting.user.name).delete_if{|n| n==current_user.name}).join(", ") %></b></p>
            <p><%= meeting.name %></p>
          </a>
        </li>
    <% end %>
  </ul>
</div>
<div data-role="collapsible" data-theme="a" data-collapsed="true" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d" data-inset="false" data-mini="true">
  <h3 style="font-size: 0.8em;">Pending Invitations&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @pending.size %></h3>
  <ul data-role="listview" data-theme="a" data-divider-theme="d">
    <% @pending.each do |meeting| %>
        <li>
          <a href="<%= meeting_path(meeting) %>" data-ajax="false">
            <h3 style="font-size: 0.8em;"><%= meeting.start_time %> hrs on <%= meeting.start_time.strftime("%d %b") %></h3>
            <p><b><%= ((meeting.meeters.select{|m| m.status}.map{|m| m.user.name} << meeting.user.name).delete_if{|n| n==current_user.name}).join(", ") %></b></p>
            <p><%= meeting.name %></p>

          </a>
        </li>
    <% end %>
  </ul>
</div>
<div data-role="collapsible" data-theme="a" data-collapsed="true" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d" data-inset="false" data-mini="true">
  <h3 style="font-size: 0.8em;">Pending Requests&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @open.size %></h3>
  <ul data-role="listview" data-theme="a" data-divider-theme="d">
    <% @open.each do |meeting| %>
        <li>
          <a href="<%= meeting_path(meeting) %>" data-ajax="false">

            <h3 style="font-size: 0.8em;"><%= meeting.start_time %> hrs on <%= meeting.start_time.strftime("%d %b") %></h3>
            <p><b><%= meeting.meeters.map{|m| m.user.name}.join(", ") %></b></p>
            <p><%= meeting.name %></p>
          </a>
        </li>
    <% end %>
  </ul>
</div>

app/views/meetings/show.html.erb
<%= content_for :page_title do %>
    Meeting
<% end %>


<h3>
  <table class="index_styling">
    <tr>
      <td class="headtd">Requestor:</td>
      <td class="normtd"><%= @meeting.user.name.titlecase %></td>
    </tr>

    <%# if !@meeter.status.nil? %>
    <tr>
      <td class="headtd">Confirmed:</td>
      <!--<td class="normtd"><%#= ((@meeting.meeters.select { |m| m.status }.map { |m| m.user.name }).delete_if { |n| n==current_user.name }).join(", ") %></td>-->
      <td class="normtd"><%= ((@meeting.meeters.select { |m| m.status }.map { |m| m.user.name })).join(", ") %></td>
    </tr>
    <%# end %>

    <%# if @meeter.status.nil? %>
    <tr>
      <td class="headtd">Tentative:</td>
      <!--<td class="normtd"><%#= ((@meeting.meeters.select { |m| m.status.nil? }.map { |m| m.user.name }).delete_if { |n| n==current_user.name }).join(", ") %></td>-->
      <td class="normtd"><%= ((@meeting.meeters.select { |m| m.status.nil? }.map { |m| m.user.name })).join(", ") %></td>
    </tr>
      <%# end %>

    <tr>
      <td class="headtd">Scheduled:</td>
      <td class="normtd"> <%= @meeting.start_time %> hrs on <%= @meeting.start_time.strftime("%m/%d/%Y") %></td>
    </tr>
    <tr>
      <td class="headtd">Location:</td>
      <td class="normtd"><%= Location.find(@meeting.location).name %></td>
    </tr>


  </table>
</h3>
<hr>

<% unless @meeting.name.blank? %>
    <div class="padded" style="font-size:0.8em;font-weight:normal;min-height: 5em;border-radius: 5px;">
      <%= @meeting.name %>
    </div>
<% end %>
<% if @meeting.user==current_user %>
    <%#= link_to "Cancel",@meeting, :method => :delete, :'data-role' => "button" %>
<% else %>
    <% if @meeter.status.nil? %>
        <%= link_to "Accept", accept_meeting_path(@meeting), :'data-role' => "button", :'data-ajax' => false,:'data-mini' => true %>
        <%#= link_to "Decline", decline_meeting_path(@meeting), :'data-role' => "button", :'data-ajax' => false %>
        <%# elsif @meeter.status %>
        <%#= link_to "Decline", decline_meeting_path(@meeting), :'data-role' => "button", :'data-ajax' => false %>
        <!--<h1>Accepted</h1>-->
        <%# else %>
        <%#= link_to "Accept", decline_meeting_path(@meeting), :'data-role' => "button", :'data-ajax' => false %>
        <!--<h1>Declined</h1>-->
    <% end %>
<% end %>


<!--<div data-role="footer" data-position="fixed" data-theme='a' data-fullscreen="true">-->
<!--<div data-role="navbar" data-theme='a'>-->
<!--<ul>-->
<!--<li><a href="/meetings/new" data-ajax='false'>New</a></li>-->
<!--<li><a href="/meetings" data-ajax='false'>Meetings</a></li>-->
<!--</ul>-->
<!--</div>-->
<!--</div>-->