config/routes.rb
ProcializeApp::Application.routes.draw do

  resources :noir_quizzes

  get "exhibitor/index"

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  match 'linkedin_desktop',:to => "desktop_view#linkedin_desktop" ,:as => "linkedin_desktop"

  get "desktop_view/index"

  get "ratings/index"

  get "speaker/index"

  get "moderator/moderator_view"

  get "moderator_view/moderator"

  match '/update_artists/:event_day_id', :to => "events#update_artists"#, :as => "update_artists"
  match '/update_songs/:event_id', :to => "events#update_songs"#, :as => "update_songs"
  match 'desktop_view/update_track/:event_day_id', :to => "desktop_view#update_track"#, :as => "update_track"
  match 'desktop_view/update_event/(:event_id)', :to => "desktop_view#update_event" #, :as => "update_event"

  resources :invitees
  resources :user_imports
  match '/excel_imp', :to => "user_imports#excel_imp" , :as => "excel_imp"

  resources :exhibitor_imports
  match '/exhibitor_excel_imp', :to => "exhibitor_imports#exhibitor_excel_imp" , :as => "exhibitor_excel_imp"

  resources :exhibitor_user_imports
  match '/exhibitor_user_excel_imp', :to => "exhibitor_user_imports#exhibitor_user_excel_imp" , :as => "exhibitor_user_excel_imp"

  mount RailsAdmin::Engine => '/organizer', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  resources :meetings
  resources :messages
  resources :events do
    resources :questionables
  end
  resources :contacts

  match 'users/:id/profile', :to => "users/profile#index", :as => "user_profile"
  match 'users/:id/profile/edit', :to => "users/profile#edit", :as => "edit_user_profile"
  match 'users/:id/follow', :to => "users/profile#following", :as => "follow"
  match '/update_status', :to => "home#update_status", :as => "update_status"

  match '/messages/focus/new/:id/(:message)/(:all)', :to => "messages#focussed_new", :as => "focussed_message"

  match '/meetings/focus/new/:id', :to => "meetings#focussed_new", :as => "focussed_meeting"

  match '/meeting_new_user', :to => "meetings#meeting_new_user", :as => "meeting_new_user"
  match '/message_new_user', :to => "messages#message_new_user", :as => "message_new_user"

  match '/show_page/event/:id', :to => 'events#show_page', :as => "show_track"
  match '/track_page/event/:id', :to => 'events#track_page', :as => "event_track"

  match '/followers_status', :to => "home#followers_status", :as => "followers_status"
  match '/accept/event/:id', :to => "events#accept", :as => "attend_event"
  match '/accept/meeting/:id', :to => "meetings#accept", :as => "accept_meeting"
  match '/decline/meeting/:id', :to => "meetings#decline", :as => "decline_meeting"
  match '/update_location', :to => "application#update_location", :as => "update_location"
  get 'search/search'
  match 'users/:id/edit', :to => "users/profile#edit", :as => "edit"
  match 'users/:id/update', :to => "users/profile#update", :as => "update"
  match '/messages/:id', :to => "messages#show"
  match '/create_question', :to => "questionables#create_question",:as => "create_question"
  match '/hide_quest', :to => "questionables#hide_quest", :as => "hide_quest"
  match '/approve_quest', :to => "questionables#approve_quest", :as => "approve_quest"
  match '/questionables/index/(:id)', :to => "questionables#index"
  match '/unapproved_view', :to => "questionables#unapproved_view"
  match '/print/(:id)', :to => "questionables#print"
  match '/graffiti', :to => "home#graffiti"
  match '/speaker', :to => "speaker#index"
  match '/ask_question', :to => "questionables#ask_question", :as => "ask_question"
  match '/ratings', :to => "ratings#index"
  match '/user_event', :to => "ratings#user_event", :as => "user_event"
  match '/rating_up', :to => "ratings#rating_up", :as => "rating_up"
  match "/send_mailers", :to => "invitees#send_mailers", :as => "send_mailers"
  match "/send_mailers_recommend", :to => "invitees#send_mailers_recommend", :as => "send_mailers_recommend" #---------for desktop------------#
  match "/search_delegates", :to => "search#search_delegates"
  match "/logos", :to => "application#logos", :as => "logos"
  match "/create_quest", :to => "events#create_quest", :as => "create_quest"

  match '/themes', :to => "home#theme_changer", :as => "themes"
  match '/users/auth/:provider/callback' => 'users/omniauth_callbacks#facebook'
  match '/voting' => "questionables#voting", :as => "voting"
  match '/concierge_service' => "home#concierge_service", :as => 'concierge_service'
  match '/order_services/:message' => "home#order_services", :as => 'order_services'
  match '/recommendation' => "home#recommendation", :as => 'recommendation'
  match '/gettweets', :to => "home#gettweets"
  match '/settweetcounter/:count', :to => "home#settweetcounter"
  match '/assets_download', :to => "home#assets_download", :as => "assets_download"
  match '/update_assets', :to => "home#update_assets", :as => "update_assets"

  match '/send_mail_to_recommended_users', :to => "home#send_mail_to_recommended_users", :as => "send_mail_to_recommended_users"
  match '/survey', :to => "home#survey"
  match '/survey_storing', :to => "home#survey_storing", :as => "survey_storing"

  match '/editing_profile', :to => "home#editing_profile", :as => "editing_profile"
  match '/editing_profile_location', :to => "home#editing_profile_location", :as => "editing_profile_location"
  match '/editing_profile_skills', :to => "home#editing_profile_skills", :as => "editing_profile_skills"
  match '/editing_profile_interest', :to => "home#editing_profile_interest", :as => "editing_profile_interest"

  match '/questions_appending/:track_id', :to => "questionables#questions_appending", :as => "questions_appending"
  match '/questions_finding', :to => "questionables#questions_finding", :as => "questions_finding"

  match '/rating_appending', :to => "ratings#rating_appending", :as => "rating_appending"
  match '/complete', :to => "meetings#complete", :as => "complete"
  match '/complete', :to => "meetings#complete", :as => "complete"

  match '/index', :to => "exhibitor#index", :as => "exhibitor"
  match '/:id/exhibitor', :to => "exhibitor#show" ,:as => "exhibitor_profile"

  match '/noir_case', :to => "noir_quizzes#noir_case", :as => "noir_case"

  resources :desktop_view

  match '/desktop_events', :to => 'desktop_view#desktop_events', :as => "desktop_events"
  match '/events_show/:id', :to => "desktop_view#events_show", :as => "events_show"
  match '/desktop_create_quest', :to => "desktop_view#desktop_create_quest", :as => "desktop_create_quest"
  match '/desktop_accept/event/:id', :to => "desktop_view#desktop_accept", :as => "desktop_accept"

  match '/feed_me', :to => "desktop_view#feed_me", :as => "feed_me"
  match '/desktop_ratings', :to => "desktop_view#desktop_ratings", :as => "desktop_ratings"
  match '/desktop_rating_appending', :to => "desktop_view#desktop_rating_appending", :as => "desktop_rating_appending"

  match '/meetings_index', :to => 'desktop_view#meetings_index', :as => "meetings_index"
  match '/desktop_focussed_new/:id', :to => "desktop_view#desktop_focussed_new", :as => "desktop_focussed_meeting"
  match '/meetings_new', :to => "desktop_view#meetings_new"
  match '/meetings_create', :to => "desktop_view#meetings_create", :as => "meetings_create"
  match '/meetings_show/:id', :to => "desktop_view#meetings_show", :as => "meetings_show"
  match '/meetings_accept/meeting/:id', :to => "desktop_view#meetings_accept", :as => "meetings_accept"
  match '/meetings_edit/:id', :to => "desktop_view#meetings_edit"
  match '/desktop_meeting_new_user', :to => "desktop_view#desktop_meeting_new_user", :as => "desktop_meeting_new_user"

  match '/messages_index', :to => 'desktop_view#messages_index', :as => "messages_index"
  match '/desktop_message_focussed_new/:id/(:message)/(:all)', :to => "desktop_view#desktop_message_focussed_new", :as => "desktop_focussed_message"
  match '/messages_new', :to => "desktop_view#messages_new", :as => "messages_new"
  match '/messages_create', :to => "desktop_view#messages_create", :as => "messages_create"
  match '/messages_show/:id', :to => "desktop_view#messages_show", :as => "messages_show"
  match '/messages_edit/:id', :to => "desktop_view#messages_edit"
  match '/messages_accept/meeting/:id', :to => "desktop_view#messages_accept", :as => "messages_accept"

  match '/delegates_search', :to => "desktop_view#delegates_search", :as => "delegates_search"
  match ':id/delegate_profile_index', :to => "desktop_view#delegate_profile_index", :as => "delegate_profile_index"
  match ':id/follow', :to => "desktop_view#desktop_following", :as => "desktop_following"
  match '/:id/desktop_edit_profile', :to => "desktop_view#desktop_edit_profile", :as => "desktop_edit_profile"
  match '/:id/desktop_update_profile', :to => "desktop_view#desktop_update_profile", :as => "desktop_update_profile"

  match '/desktop_graffiti', :to => "desktop_view#desktop_graffiti", :as => "desktop_graffiti"

  match '/desktop_assets_download', :to => "desktop_view#desktop_assets_download", :as => 'desktop_assets_download'

  match '/desktop_speaker', :to => "desktop_view#desktop_speaker", :as => 'desktop_speaker'

  match '/concierge_service_desktop', :to => "desktop_view#concierge_service_desktop", :as => "concierge_service_desktop"
  match '/order_services_desktop/:message', :to => "desktop_view#order_services_desktop", :as => "order_services_desktop"

``#----------Contact Us-------------#
  match '/contact_us_new', :to => "desktop_view#contact_us_new", :as => "contact_us_new"
  match '/contact_us_create', :to => "desktop_view#contact_us_create", :as => "contact_us_create"

``#----------Questionables-------------#
  match '/desktop_ask_question', :to => "desktop_view#desktop_ask_question", :as => "desktop_ask_question"

app/models/exhibitor.rb
class Exhibitor < ActiveRecord::Base
  attr_accessible :brouchers, :description, :exhi_logo, :industry, :name, :stall_no,:broucher2,:contact_no,:viewers_name

  has_attached_file :brouchers, :content_type => ["application/xls","application/xlsx","application/pdf","image/png","image/jpg"]
  has_attached_file :broucher2, :content_type => ["application/xls","application/xlsx","application/pdf","image/png","image/jpg"]
  has_attached_file :exhi_logo


 has_many :exhibitor_users,:dependent => :destroy
 has_many :users,:through => :exhibitor_users

end

app/controllers/exhibitor_controller.rb
class ExhibitorController < ApplicationController
  def index
   @exhibitor=Exhibitor.all
  end

  def show
    @exhibitor=Exhibitor.find(params[:id])
    @exhi_name=@exhibitor.name
    @exhi_industry=@exhibitor.industry
    @exhi_description=@exhibitor.description
    @exhi_stall=@exhibitor.stall_no
    @exhi_stall=@exhibitor.contact_no

    @user_id=Array.new
    @exhi_user=ExhibitorUser.find_all_by_exhibitor_id(@exhibitor.id)
    @exhi_user.each do |u|
       @user_id<<u.user_id
    end

    @user_name=User.find(@user_id)


    if @exhibitor!=current_user
      if !@exhibitor.viewers_name.blank?
        @viewers_name=@exhibitor.viewers_name
        @person_name=@viewers_name.split('|').last
        @person=@person_name.split(':').first.to_i + 1
        @viewing=@person.to_s+':'+current_user.name
        @exhibitor.viewers_name=@viewers_name +'|'+@viewing
      else
        @exhibitor.viewers_name="1:#{current_user.name}"
      end
      @exhibitor.save
    end

  end
end

app/helpers/exhibitor_helper.rb
module ExhibitorHelper
end

app/views/exhibitor/index.html.erb
<%= content_for :page_title do %>
    Find Exhibitor
<% end %>


<ul data-role="listview" data-theme="a" data-divider-theme="d" data-split-icon='star' data-mini="true" data-filter="true">
  <% @exhibitor.sort_by(&:name).each do |e| %>
  <li data-theme='a' data-filtertext=" <%= e.name %> <%= e.industry %>">
    <a style="font-size: 0.8em;" href="<%= exhibitor_profile_path(e.id) %>" data-ajax=false data-theme='a'>
      <%= e.name %>
    </a>
  </li>
  <% end %>
</ul>



<script type="text/javascript">
    function follow_search(id) {
        $.ajax({
            url:"/users/" + id + "/follow",
            type:"post",
            success:function (data) {
                if (data == "Unfollow") {
                    $('#user' + id).parent().attr('data-theme', 'b').removeClass("ui-btn-up-a").addClass("ui-btn-up-b");
                    $('#user' + id).prev().find('.ui-link-inherit').append('<span id="following' + id + '" class="highlighted" >Following</span>');
                } else {
                    $('#user' + id).parent().attr('data-theme', 'a').removeClass("ui-btn-up-b").addClass("ui-btn-up-a");
                    $("#following" + id).remove();
                }
            }
        });
    }

</script>



<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41279198-1', '127.0.0.1:3000');
    ga('send', 'pageview');

</script>

app/views/exhibitor/show.html.erb
<%= content_for :page_title do %>
    Profile
<% end %>


<div style="background: none;"  class="fbinfobox">
<% if !@exhibitor.exhi_logo.blank? %><%= image_tag @exhibitor.exhi_logo.url, :style => "border-radius:5px;margin-right:10px;max-width:80px" %><br><% end %>


<h4 style="margin-top: 0px;color: #ffffff;font-size: 1.1em;">
  <span style="font-weight: bold;font-size: 1.1em;"><%= @exhi_name.titlecase %></span>
  <table style="table-layout: fixed;width:100%;">
    <tr><td  style="background: none;color: #ffffff;box-shadow:none;word-wrap: break-word;"><% if !@exhibitor.industry.blank? %><small><strong style="color: #c0c0c0;">Industry: </strong><%= @exhibitor.industry %> </small><% end %></td></tr>

    <tr><td style="background: none;color: white;box-shadow:none;word-wrap: break-word;"><% if !@exhibitor.description.blank? %><small><strong style="color: #c0c0c0;">Details: </strong><%= raw @exhibitor.description %></small><br><% end %></td></tr>

    <tr><td><% if !@exhibitor.stall_no.blank? %><small><strong style="color: #c0c0c0;">Stall No: </strong><%= @exhibitor.stall_no %></small><br><% end %></td></tr>

    <tr><td><% if !@exhibitor.contact_no.blank? %><small><strong style="color: #c0c0c0;">Contact No: </strong><%= @exhibitor.contact_no %></small><br><% end %></td></tr>

    <tr><td><% if !@exhibitor.brouchers.blank? %><small><a target="_blank"  href="<%=@exhibitor.brouchers.url%>" data-ajax=false data-role=button data-mini=true>Company Brochure</a></small><% end %></td></tr>

    <tr><td><% if !@exhibitor.broucher2.blank? %><small><a target="_blank"  href="<%=@exhibitor.broucher2.url%>" data-ajax=false data-role=button data-mini=true>Product Brochure</a></small><% end %></td></tr>

    <tr>
        <td style="background: none;color: white;box-shadow:none;word-wrap: break-word;">
          <small>
            <% @user_name.each do |u|  %>
                <table style="table-layout: fixed;width:100%;">
                  <% if !u.name.nil? %>
                  <tr>
                    <strong style="color: #c0c0c0;">Person: </strong>
                    <td align="position"valign="position" style="background: none;color: white;box-shadow:none;word-wrap: break-word;"><%= u.name %></td>
                  </tr>
                  <tr>
                    <td align="position"valign="position" style="background: none;color: white;box-shadow:none;word-wrap: break-word;"><%= link_to "Request Meeting", focussed_meeting_path(u), :'data-role' => "button", :'data-theme' => "a",:'data-ajax' => false, :'data-mini' => true %></td>
                    <td align="position"valign="position" style="background: none;color: white;box-shadow:none;word-wrap: break-word;"><%= link_to "Send Message", focussed_message_path(u)+'/?reply=true', :'data-role' => "button", :'data-theme' => "a", :'data-ajax' => false, :'data-mini' => true %></td>
                  </tr>
                   <% end %>
                </table>
            <% end %>
          </small>
        </td>
    </tr>
  </table>

</h4>
</div>


<style type="text/css">
    small{
        font-size: 100%;
    }
</style>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41279198-1', '127.0.0.1:3000');
    ga('send', 'pageview');

</script>