config/routes.rb
ProcializeApp::Application.routes.draw do

  resources :noir_quizzes

  get "exhibitor/index"

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  match 'linkedin_desktop',:to => "desktop_view#linkedin_desktop" ,:as => "linkedin_desktop"

  get "desktop_view/index"

  get "ratings/index"

  get "speaker/index"

  get "moderator/moderator_view"

  get "moderator_view/moderator"

  match '/update_artists/:event_day_id', :to => "events#update_artists"#, :as => "update_artists"
  match '/update_songs/:event_id', :to => "events#update_songs"#, :as => "update_songs"
  match 'desktop_view/update_track/:event_day_id', :to => "desktop_view#update_track"#, :as => "update_track"
  match 'desktop_view/update_event/(:event_id)', :to => "desktop_view#update_event" #, :as => "update_event"

  resources :invitees
  resources :user_imports
  match '/excel_imp', :to => "user_imports#excel_imp" , :as => "excel_imp"

  resources :exhibitor_imports
  match '/exhibitor_excel_imp', :to => "exhibitor_imports#exhibitor_excel_imp" , :as => "exhibitor_excel_imp"

  resources :exhibitor_user_imports
  match '/exhibitor_user_excel_imp', :to => "exhibitor_user_imports#exhibitor_user_excel_imp" , :as => "exhibitor_user_excel_imp"

  mount RailsAdmin::Engine => '/organizer', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  resources :meetings
  resources :messages
  resources :events do
    resources :questionables
  end
  resources :contacts

  match 'users/:id/profile', :to => "users/profile#index", :as => "user_profile"
  match 'users/:id/profile/edit', :to => "users/profile#edit", :as => "edit_user_profile"
  match 'users/:id/follow', :to => "users/profile#following", :as => "follow"
  match '/update_status', :to => "home#update_status", :as => "update_status"

  match '/messages/focus/new/:id/(:message)/(:all)', :to => "messages#focussed_new", :as => "focussed_message"

  match '/meetings/focus/new/:id', :to => "meetings#focussed_new", :as => "focussed_meeting"

  match '/meeting_new_user', :to => "meetings#meeting_new_user", :as => "meeting_new_user"
  match '/message_new_user', :to => "messages#message_new_user", :as => "message_new_user"

  match '/show_page/event/:id', :to => 'events#show_page', :as => "show_track"
  match '/track_page/event/:id', :to => 'events#track_page', :as => "event_track"

  match '/followers_status', :to => "home#followers_status", :as => "followers_status"
  match '/accept/event/:id', :to => "events#accept", :as => "attend_event"
  match '/accept/meeting/:id', :to => "meetings#accept", :as => "accept_meeting"
  match '/decline/meeting/:id', :to => "meetings#decline", :as => "decline_meeting"
  match '/update_location', :to => "application#update_location", :as => "update_location"
  get 'search/search'
  match 'users/:id/edit', :to => "users/profile#edit", :as => "edit"
  match 'users/:id/update', :to => "users/profile#update", :as => "update"
  match '/messages/:id', :to => "messages#show"
  match '/create_question', :to => "questionables#create_question",:as => "create_question"
  match '/hide_quest', :to => "questionables#hide_quest", :as => "hide_quest"
  match '/approve_quest', :to => "questionables#approve_quest", :as => "approve_quest"
  match '/questionables/index/(:id)', :to => "questionables#index"
  match '/unapproved_view', :to => "questionables#unapproved_view"
  match '/print/(:id)', :to => "questionables#print"
  match '/graffiti', :to => "home#graffiti"
  match '/speaker', :to => "speaker#index"
  match '/ask_question', :to => "questionables#ask_question", :as => "ask_question"
  match '/ratings', :to => "ratings#index"
  match '/user_event', :to => "ratings#user_event", :as => "user_event"
  match '/rating_up', :to => "ratings#rating_up", :as => "rating_up"
  match "/send_mailers", :to => "invitees#send_mailers", :as => "send_mailers"
  match "/send_mailers_recommend", :to => "invitees#send_mailers_recommend", :as => "send_mailers_recommend" #---------for desktop------------#
  match "/search_delegates", :to => "search#search_delegates"
  match "/logos", :to => "application#logos", :as => "logos"
  match "/create_quest", :to => "events#create_quest", :as => "create_quest"

  match '/themes', :to => "home#theme_changer", :as => "themes"
  match '/users/auth/:provider/callback' => 'users/omniauth_callbacks#facebook'
  match '/voting' => "questionables#voting", :as => "voting"
  match '/concierge_service' => "home#concierge_service", :as => 'concierge_service'
  match '/order_services/:message' => "home#order_services", :as => 'order_services'
  match '/recommendation' => "home#recommendation", :as => 'recommendation'
  match '/gettweets', :to => "home#gettweets"
  match '/settweetcounter/:count', :to => "home#settweetcounter"
  match '/assets_download', :to => "home#assets_download", :as => "assets_download"
  match '/update_assets', :to => "home#update_assets", :as => "update_assets"

  match '/send_mail_to_recommended_users', :to => "home#send_mail_to_recommended_users", :as => "send_mail_to_recommended_users"
  match '/survey', :to => "home#survey"
  match '/survey_storing', :to => "home#survey_storing", :as => "survey_storing"

  match '/editing_profile', :to => "home#editing_profile", :as => "editing_profile"
  match '/editing_profile_location', :to => "home#editing_profile_location", :as => "editing_profile_location"
  match '/editing_profile_skills', :to => "home#editing_profile_skills", :as => "editing_profile_skills"
  match '/editing_profile_interest', :to => "home#editing_profile_interest", :as => "editing_profile_interest"

  match '/questions_appending/:track_id', :to => "questionables#questions_appending", :as => "questions_appending"
  match '/questions_finding', :to => "questionables#questions_finding", :as => "questions_finding"

  match '/rating_appending', :to => "ratings#rating_appending", :as => "rating_appending"
  match '/complete', :to => "meetings#complete", :as => "complete"
  match '/complete', :to => "meetings#complete", :as => "complete"

  match '/index', :to => "exhibitor#index", :as => "exhibitor"
  match '/:id/exhibitor', :to => "exhibitor#show" ,:as => "exhibitor_profile"

  match '/noir_case', :to => "noir_quizzes#noir_case", :as => "noir_case"

  resources :desktop_view

  match '/desktop_events', :to => 'desktop_view#desktop_events', :as => "desktop_events"
  match '/events_show/:id', :to => "desktop_view#events_show", :as => "events_show"
  match '/desktop_create_quest', :to => "desktop_view#desktop_create_quest", :as => "desktop_create_quest"
  match '/desktop_accept/event/:id', :to => "desktop_view#desktop_accept", :as => "desktop_accept"

  match '/feed_me', :to => "desktop_view#feed_me", :as => "feed_me"
  match '/desktop_ratings', :to => "desktop_view#desktop_ratings", :as => "desktop_ratings"
  match '/desktop_rating_appending', :to => "desktop_view#desktop_rating_appending", :as => "desktop_rating_appending"

  match '/meetings_index', :to => 'desktop_view#meetings_index', :as => "meetings_index"
  match '/desktop_focussed_new/:id', :to => "desktop_view#desktop_focussed_new", :as => "desktop_focussed_meeting"
  match '/meetings_new', :to => "desktop_view#meetings_new"
  match '/meetings_create', :to => "desktop_view#meetings_create", :as => "meetings_create"
  match '/meetings_show/:id', :to => "desktop_view#meetings_show", :as => "meetings_show"
  match '/meetings_accept/meeting/:id', :to => "desktop_view#meetings_accept", :as => "meetings_accept"
  match '/meetings_edit/:id', :to => "desktop_view#meetings_edit"
  match '/desktop_meeting_new_user', :to => "desktop_view#desktop_meeting_new_user", :as => "desktop_meeting_new_user"

  match '/messages_index', :to => 'desktop_view#messages_index', :as => "messages_index"
  match '/desktop_message_focussed_new/:id/(:message)/(:all)', :to => "desktop_view#desktop_message_focussed_new", :as => "desktop_focussed_message"
  match '/messages_new', :to => "desktop_view#messages_new", :as => "messages_new"
  match '/messages_create', :to => "desktop_view#messages_create", :as => "messages_create"
  match '/messages_show/:id', :to => "desktop_view#messages_show", :as => "messages_show"
  match '/messages_edit/:id', :to => "desktop_view#messages_edit"
  match '/messages_accept/meeting/:id', :to => "desktop_view#messages_accept", :as => "messages_accept"

  match '/delegates_search', :to => "desktop_view#delegates_search", :as => "delegates_search"
  match ':id/delegate_profile_index', :to => "desktop_view#delegate_profile_index", :as => "delegate_profile_index"
  match ':id/follow', :to => "desktop_view#desktop_following", :as => "desktop_following"
  match '/:id/desktop_edit_profile', :to => "desktop_view#desktop_edit_profile", :as => "desktop_edit_profile"
  match '/:id/desktop_update_profile', :to => "desktop_view#desktop_update_profile", :as => "desktop_update_profile"

  match '/desktop_graffiti', :to => "desktop_view#desktop_graffiti", :as => "desktop_graffiti"

  match '/desktop_assets_download', :to => "desktop_view#desktop_assets_download", :as => 'desktop_assets_download'

  match '/desktop_speaker', :to => "desktop_view#desktop_speaker", :as => 'desktop_speaker'

  match '/concierge_service_desktop', :to => "desktop_view#concierge_service_desktop", :as => "concierge_service_desktop"
  match '/order_services_desktop/:message', :to => "desktop_view#order_services_desktop", :as => "order_services_desktop"

``#----------Contact Us-------------#
  match '/contact_us_new', :to => "desktop_view#contact_us_new", :as => "contact_us_new"
  match '/contact_us_create', :to => "desktop_view#contact_us_create", :as => "contact_us_create"

``#----------Questionables-------------#
  match '/desktop_ask_question', :to => "desktop_view#desktop_ask_question", :as => "desktop_ask_question"

app/models/questionable.rb
class Questionable < ActiveRecord::Base
  attr_accessible :approved, :down_votes, :event_id, :quest_name, :up_votes, :user_id ,:track_id

  #belongs_to :event
   belongs_to :track



end

app/controllers/questionables_controller.rb
class QuestionablesController < ApplicationController


  # GET /questionables
  # GET /questionables.json
  #load_and_authorize_resource
  def index
    @user=current_user
    if params[:id].blank?
      @tracks=Questionable.all.map { |i| i.track_id }.uniq
    else
      @track=Track.find(params[:id]).id
      @tracks=Array.new
      @tracks<<@track
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questionables }
    end
  end


  # GET /questionables/1
  # GET /questionables/1.json
  def show
    @questionable = Questionable.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @questionable }
    end
  end

  # GET /questionables/new
  # GET /questionables/new.json
  def new
    @questionable = Questionable.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @questionable }
    end
  end

  # GET /questionables/1/edit
  def edit
    @questionable = Questionable.find(params[:id])
  end

  # POST /questionables
  # POST /questionables.json
  def create
    @user=current_user
    @event = Event.find(params[:event_id])
    @questionable = @event.questionables.create(params[:questionable])
    redirect_to event_path(@event)
  end

  def ask_question
    @user=current_user
    @event_days=@conference.event_days
    @event_days = EventDay.all
    @events = Event.all
    @tracks = Track.all
    if (!@track.nil?)
      @track = Track.find(params[:track_id])
    end
    if (!@questionable.nil?)
      @questionable = @track.questionables.create(params[:questionable])
    end
  end



  def create_question
    @user=current_user
    unless params[:questionable].blank?
      @track=Questionable.create(:track_id => params[:question_appending][0], :quest_name => params[:questionable][:quest_name], :user_id => @user.id, :approved => true)
    end
    render :text => @track.save
    return
  end


  # PUT /questionables/1
  # PUT /questionables/1.json
  def update
    @questionable = Questionable.find(params[:id])
    respond_to do |format|
      if @questionable.update_attributes(params[:questionable])
        format.html { redirect_to @questionable, notice: 'Questionable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @questionable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionables/1
  # DELETE /questionables/1.json
  def destroy
    @event = Event.find(params[:event_id])
    @questionable = @event.questionables.find(params[:id])
    @questionable.destroy
    redirect_to event_path(@event)
  end


  def hide_quest
    @questionable=Questionable.find(params[:question_id][0])
    @questionable.hide=true
    @questionable.save
    render :text => @questionable.id
    return
  end


  def approve_quest
    @questionable=Questionable.find(params[:question_id][0])
    @questionable.approved=true
    @questionable.hide=nil
    @questionable.save
    render :text => @questionable.id
    return
  end


  def unapproved_view
    @events=Questionable.all.map { |i| i.event_id }.uniq
    @unapproved = Questionable.where(:hide => true).all
  end

  def print
    @user=current_user
    if params[:id].blank?
      @tracks=Questionable.all.map { |i| i.track_id }.uniq
    else
      @track=Track.find(params[:id])
      @tracks=Array.new
      @tracks<<@track
    end

    render :layout => false
  end




  def voting
    @questionable=Questionable.find(params[:question_id][0])
    @questionable.like=@questionable.like+1
    @questionable.liking_by=@questionable.liking_by+','+"#{current_user.id}"
    @questionable.save
    render :text => @questionable.like
  end




  def questions_appending
    @quest=Questionable.find_all_by_track_id_and_approved(params[:track_id], true).sort_by(&:like).reverse
    @return_data=Array.new
    @quest.each do |i|
      if i.liking_by.include? current_user.id.to_s
        @like_return=1
      else
        @like_return=0
      end
      @return_data<<"#{i.id}|#{i.quest_name}|#{i.user_id}|#{User.find(i.user_id).name}|#{i.like}|#{i.liking_by}|#{@like_return}"
    end
    render :json => @return_data
  end


end

app/helpers/questionables_helper.rb
module QuestionablesHelper
end

app/views/questionables/ask_question.html.erb
<%= content_for :page_title do %>
    Questions
<% end %>





<div data-role="content" id="categoriesContent">
  <ul data-role="listview" data-theme="d" data-dividertheme="c" data-counttheme="b" style="font-size: 0.8em;font-family: helveticaneue;">
    <% Questionable.where(:approved => true).reverse.each do |e| %>
        <% if !e.quest_name.nil?   %>
            <li><%= e.quest_name %>  asked by <%= User.find(e.user_id).name %> at <%= Track.find(e.track_id).name %></li>
        <% end %>
    <% end %>
  </ul>
</div>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41279198-1', '127.0.0.1:3000');
    ga('send', 'pageview');

</script>

app/views/questionables/edit.html.erb
<h1>Editing questionable</h1>

<%= render 'form' %>

<%= link_to 'Show', @questionable %> |
<%= link_to 'Back', questionables_path %>

app/views/questionables/index.html.erb
<style>
    td {
        padding: 10px;
    }


</style>


<script type="text/javascript">
    $(function () {
        $('.approve').click(function () {
//          alert($(this).parent().parent().prev().attr('id'));
            var data = {question_id:[]}
            data["question_id"].push($(this).parent().parent().prev().attr('id'));
//          alert($(this).parent().parent().prev().prev().attr('id'));

            $.ajax({
                url:"<%= approve_quest_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    var this_div = "#question_div_" + data;
                    $(this_div).hide();

                }
            });

        });


        $('.hide').click(function () {
//          alert($(this).parent().parent().prev().prev().attr('id'));

            var data = {question_id:[]}
            data["question_id"].push($(this).parent().parent().prev().prev().attr('id'));
//          alert($(this).parent().parent().prev().prev().attr('id'));

            $.ajax({
                url:"<%= hide_quest_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    var this_div = "#question_div_" + data;
                    $(this_div).hide();
                }
            });

        });


    })


    $(function () {
        $('.likes').bind("click",function () {
            var a = $(this).parent().parent().parent().parent().parent().parent().attr('id');
            $(this).unbind('click');
            a = a.replace('question_div_', "");
            var data = {question_id:[]}
            data["question_id"].push(a);
            $.ajax({
                url:"<%= voting_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    $('#like_' + a).html(data);

                }
            });

        });

    });


</script>


<div>
  <ul data-role="listview" data-theme="a" data-divider-theme="d" data-filter-placeholder="Search by events" data-split-icon='star' data-mini="true" data-filter="true">
    <% if params[:id].blank? %>
        <% if @user.role=="proops" || @user.role=="orgops" %>
            <a href="/print" data-role="button" data-icon="print" data-iconpos="notext" target="_blank" data-mini="true">Print
              all</a>
        <% end %>
    <% end %>
    <% @tracks.each do |e| %>
        <% unless e.nil? %>
            <% @track_name =Track.find(e).name %>
        <% end %>

        <% @questionable = Questionable.order("like DESC").order("created_at DESC").find_all_by_track_id_and_approved(e, true) %>
        <% @questionable.each do |q| %>
            <li>
              <h2 style="font-size: 0.8em;"><%= @track_name %></h2>
              <% if @user.role=="proops" || @user.role=="orgops" %>
                  <a href="/print/<%= e.id %>" data-role="button" data-icon="print" data-iconpos="notext" target="_blank" data-mini="true">Print</a>
              <% end %>
              <div id="question_div_<%= q.id %>">
                <p><%= User.find(q.user_id).name.titleize %><span style="font-size: 0.8em;font-weight: normal;">&nbsp;&nbsp;
                  asked</span> &nbsp;&nbsp;" <%= q.quest_name.titleize %>"
                </p>
                <table>
                  <tr>
                    <% if !q.liking_by.split(",").include? current_user.id.to_s %>
                        <td id="<%= q.id %>">
                          <input data-icon="thumbs-up" data-iconpos="notext" type="button" value="Likes" class="likes" id="liking">
                        </td>
                    <% end %>
                    <td><h5 id="like_<%= q.id %>"><%= q.like %> Likes </h5></td>
                  </tr>
                </table>
              </div>
            </li>
        <% end %>
    <% end %>
  </ul>
  <br>
</div>

app/views/questionables/new.html.erb
<h1>New questionable</h1>

<%= render 'form' %>

<%= link_to 'Back', questionables_path %>

app/views/questionables/print.html.erb
<script type="text/javascript">
    $(function () {
        $('.approve').click(function () {
//          alert($(this).parent().parent().prev().attr('id'));
            var data = {question_id:[]}
            data["question_id"].push($(this).parent().parent().prev().attr('id'));
//          alert($(this).parent().parent().prev().prev().attr('id'));

            $.ajax({
                url:"<%= approve_quest_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    var this_div = "#question_div_" + data;
                    $(this_div).hide();

                }
            });

        });



        $('.hide').click(function () {
//          alert($(this).parent().parent().prev().prev().attr('id'));

            var data = {question_id:[]}
            data["question_id"].push($(this).parent().parent().prev().prev().attr('id'));
//          alert($(this).parent().parent().prev().prev().attr('id'));

            $.ajax({
                url:"<%= hide_quest_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    var this_div = "#question_div_" + data;
                    $(this_div).hide();
                }
            });

        });


    })
</script>



<!--<a href="index.html" data-role="button" target="_blank">Link button</a>-->
<% @tracks.each do |e| %>
    <% unless e.nil? %>
        <% @track_name =Track.find(e).name %>
    <% end %>
    <h4 style="font-size: 0.8em;">  <%= @track_name %>  </h4>
    <% @questionable = Questionable.find_all_by_track_id_and_approved(e,true) %>
    <% @questionable.each do |q| %>
        <div style="background: rgba(178,204,255,0.93); width:98%;padding-left:5px;padding-top:4px;padding-bottom:4px;border-radius:5px;font-weight: normal;">
          <span style="color:#333333;font-size:0.8em;font-weight:normal;"><%= User.find(q.user_id).name.titleize %></span>
          <span style="color:#333333;font-size:0.8em;font-weight:normal;">asked</span>
        </div>

        <div style="font-size: 0.8em;margin-top: 5px;"> <%= q.quest_name.titleize %></div>
        <table>
          <tr>
            <td><h5 id="like_<%= q.id %>"><%= q.like %> Likes</h5></td>
          </tr>
        </table>
        </div>
        <br>

    <% end %>
<% end %>

app/views/questionables/question_view.html.erb
<style>
    td {
        padding: 10px;
    }

    .fbinfo {
        background-color: rgb(244, 191, 71);
        color: #333333;
        padding: 10px;
        border-radius: 10px;
        -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        font-weight: bold;
    }

</style>


<script type="text/javascript">
    $(function () {
        $('.approve').click(function () {
            var a =  $(this).parent().parent().parent().parent().parent().parent().attr('id')
            a= a.replace('question_div_',"");
            var data = {question_id:[]}
            data["question_id"].push(a);
//          alert($(this).parent().parent().prev().prev().attr('id'));

            $.ajax({
                url:"<%= approve_quest_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    var this_div = "#question_div_" + data;
                    $(this_div).hide();
                }
            });

        });



        $('.hide').click(function () {
            var data = {question_id:[]}
            data["question_id"].push($(this).parent().parent().prev().prev().attr('id'));

            $.ajax({
                url:"<%= hide_quest_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    var this_div = "#question_div_" + data;
                    $(this_div).hide();
                }
            });

        });


    })
</script>

<div>
  <ul data-role="listview" data-theme="a" data-divider-theme="d" data-filter-placeholder="Search by events" data-split-icon='star' data-mini="true" data-filter="true">
    <% @tracks=Questionable.all.map { |i| i.track_id }.uniq %>
    <% @tracks.each do |e| %>
        <% unless e.nil? %>
            <% @track_name =Track.find(e).name %>
        <% end %>

        <% @questionable1 = Questionable.find_all_by_track_id_and_hide(e,nil) %>
        <% @questionable2 = Questionable.find_all_by_track_id_and_approved(e,false) %>


        <% @questionable = (@questionable2&@questionable1) %>

        <% @questionable.each do |q| %>
            <li>
              <h2 style="font-size: 0.8em;"><%= @track_name %></h2>
              <div id="question_div_<%= q.id %>">
                <p><%= User.find(q.user_id).name.titleize %><span style="font-size: 0.8em;font-weight: normal;">&nbsp;&nbsp;
                  asked</span> &nbsp;&nbsp;" <%= q.quest_name.titleize %>"
                </p>
                <table>
                  <tr>
                    <td><%= hidden_field_tag q.id %></td>
                    <td><input type="button" value="Approve" class="approve" data-mini="true"></td>
                  </tr>
                </table>
              </div>
            </li>
        <% end %>
    <% end %>
  </ul>
  <br>
</div>

app/views/questionables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @questionable.event_id %>
</p>

<p>
  <b>User:</b>
  <%= @questionable.user_id %>
</p>

<p>
  <b>Approved:</b>
  <%= @questionable.approved %>
</p>

<p>
  <b>Quest name:</b>
  <%= @questionable.quest_name %>
</p>

<p>
  <b>Up votes:</b>
  <%= @questionable.up_votes %>
</p>

<p>
  <b>Down votes:</b>
  <%= @questionable.down_votes %>
</p>


<%= link_to 'Edit', edit_questionable_path(@questionable) %> |
<%= link_to 'Back', questionables_path %>

app/views/questionables/unapproved_view.html.erb
<style>
    td {
        padding: 10px;
    }

    .fbinfo {
        background-color: rgb(244, 191, 71);
        color: #333333;
        padding: 10px;
        border-radius: 10px;
        -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        font-weight: bold;
    }

</style>


<script type="text/javascript">
    $(function () {
        $('.approve').click(function () {
            var data = {question_id:[]}
            data["question_id"].push($(this).parent().parent().prev().attr('id'));

            $.ajax({
                url:"<%= approve_quest_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    var this_div = "#question_div_" + data;
                    $(this_div).hide();

                }
            });

        });



        $('.hide').click(function () {

            var data = {question_id:[]}
            data["question_id"].push($(this).parent().parent().prev().prev().attr('id'));

            $.ajax({
                url:"<%= hide_quest_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {
                    var this_div = "#question_div_" + data;
                    $(this_div).hide();
                }
            });

        });


    })
</script>





<% @events.each do |e| %>
    <% @event_name =Event.find(e).name %>
    <h1>  <%= @event_name %>  </h1>
    <% @questionable = Questionable.find_all_by_event_id_and_hide(e,true) %>


    <% @questionable.each do |q| %>
        <div class="fbinfo" id="question_div_<%= q.id %>">
          <table>
            <tr>
              <td><%= User.find(q.user_id).name.titleize %></td>
              <td>asked</td>
              <td><h3> <%= q.quest_name.titleize %></h3></td>


              <%= hidden_field_tag q.id %>
              <td><input type="button" value="Approve" class="approve"></td>



            </tr>
          </table>
        </div>
        <br>
    <% end %>
    <br>


<% end %>