config/routes.rb
ProcializeApp::Application.routes.draw do

  resources :noir_quizzes

  get "exhibitor/index"

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  match 'linkedin_desktop',:to => "desktop_view#linkedin_desktop" ,:as => "linkedin_desktop"

  get "desktop_view/index"

  get "ratings/index"

  get "speaker/index"

  get "moderator/moderator_view"

  get "moderator_view/moderator"

  match '/update_artists/:event_day_id', :to => "events#update_artists"#, :as => "update_artists"
  match '/update_songs/:event_id', :to => "events#update_songs"#, :as => "update_songs"
  match 'desktop_view/update_track/:event_day_id', :to => "desktop_view#update_track"#, :as => "update_track"
  match 'desktop_view/update_event/(:event_id)', :to => "desktop_view#update_event" #, :as => "update_event"

  resources :invitees
  resources :user_imports
  match '/excel_imp', :to => "user_imports#excel_imp" , :as => "excel_imp"

  resources :exhibitor_imports
  match '/exhibitor_excel_imp', :to => "exhibitor_imports#exhibitor_excel_imp" , :as => "exhibitor_excel_imp"

  resources :exhibitor_user_imports
  match '/exhibitor_user_excel_imp', :to => "exhibitor_user_imports#exhibitor_user_excel_imp" , :as => "exhibitor_user_excel_imp"

  mount RailsAdmin::Engine => '/organizer', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  resources :meetings
  resources :messages
  resources :events do
    resources :questionables
  end
  resources :contacts

  match 'users/:id/profile', :to => "users/profile#index", :as => "user_profile"
  match 'users/:id/profile/edit', :to => "users/profile#edit", :as => "edit_user_profile"
  match 'users/:id/follow', :to => "users/profile#following", :as => "follow"
  match '/update_status', :to => "home#update_status", :as => "update_status"

  match '/messages/focus/new/:id/(:message)/(:all)', :to => "messages#focussed_new", :as => "focussed_message"

  match '/meetings/focus/new/:id', :to => "meetings#focussed_new", :as => "focussed_meeting"

  match '/meeting_new_user', :to => "meetings#meeting_new_user", :as => "meeting_new_user"
  match '/message_new_user', :to => "messages#message_new_user", :as => "message_new_user"

  match '/show_page/event/:id', :to => 'events#show_page', :as => "show_track"
  match '/track_page/event/:id', :to => 'events#track_page', :as => "event_track"

  match '/followers_status', :to => "home#followers_status", :as => "followers_status"
  match '/accept/event/:id', :to => "events#accept", :as => "attend_event"
  match '/accept/meeting/:id', :to => "meetings#accept", :as => "accept_meeting"
  match '/decline/meeting/:id', :to => "meetings#decline", :as => "decline_meeting"
  match '/update_location', :to => "application#update_location", :as => "update_location"
  get 'search/search'
  match 'users/:id/edit', :to => "users/profile#edit", :as => "edit"
  match 'users/:id/update', :to => "users/profile#update", :as => "update"
  match '/messages/:id', :to => "messages#show"
  match '/create_question', :to => "questionables#create_question",:as => "create_question"
  match '/hide_quest', :to => "questionables#hide_quest", :as => "hide_quest"
  match '/approve_quest', :to => "questionables#approve_quest", :as => "approve_quest"
  match '/questionables/index/(:id)', :to => "questionables#index"
  match '/unapproved_view', :to => "questionables#unapproved_view"
  match '/print/(:id)', :to => "questionables#print"
  match '/graffiti', :to => "home#graffiti"
  match '/speaker', :to => "speaker#index"
  match '/ask_question', :to => "questionables#ask_question", :as => "ask_question"
  match '/ratings', :to => "ratings#index"
  match '/user_event', :to => "ratings#user_event", :as => "user_event"
  match '/rating_up', :to => "ratings#rating_up", :as => "rating_up"
  match "/send_mailers", :to => "invitees#send_mailers", :as => "send_mailers"
  match "/send_mailers_recommend", :to => "invitees#send_mailers_recommend", :as => "send_mailers_recommend" #---------for desktop------------#
  match "/search_delegates", :to => "search#search_delegates"
  match "/logos", :to => "application#logos", :as => "logos"
  match "/create_quest", :to => "events#create_quest", :as => "create_quest"

  match '/themes', :to => "home#theme_changer", :as => "themes"
  match '/users/auth/:provider/callback' => 'users/omniauth_callbacks#facebook'
  match '/voting' => "questionables#voting", :as => "voting"
  match '/concierge_service' => "home#concierge_service", :as => 'concierge_service'
  match '/order_services/:message' => "home#order_services", :as => 'order_services'
  match '/recommendation' => "home#recommendation", :as => 'recommendation'
  match '/gettweets', :to => "home#gettweets"
  match '/settweetcounter/:count', :to => "home#settweetcounter"
  match '/assets_download', :to => "home#assets_download", :as => "assets_download"
  match '/update_assets', :to => "home#update_assets", :as => "update_assets"

  match '/send_mail_to_recommended_users', :to => "home#send_mail_to_recommended_users", :as => "send_mail_to_recommended_users"
  match '/survey', :to => "home#survey"
  match '/survey_storing', :to => "home#survey_storing", :as => "survey_storing"

  match '/editing_profile', :to => "home#editing_profile", :as => "editing_profile"
  match '/editing_profile_location', :to => "home#editing_profile_location", :as => "editing_profile_location"
  match '/editing_profile_skills', :to => "home#editing_profile_skills", :as => "editing_profile_skills"
  match '/editing_profile_interest', :to => "home#editing_profile_interest", :as => "editing_profile_interest"

  match '/questions_appending/:track_id', :to => "questionables#questions_appending", :as => "questions_appending"
  match '/questions_finding', :to => "questionables#questions_finding", :as => "questions_finding"

  match '/rating_appending', :to => "ratings#rating_appending", :as => "rating_appending"
  match '/complete', :to => "meetings#complete", :as => "complete"
  match '/complete', :to => "meetings#complete", :as => "complete"

  match '/index', :to => "exhibitor#index", :as => "exhibitor"
  match '/:id/exhibitor', :to => "exhibitor#show" ,:as => "exhibitor_profile"

  match '/noir_case', :to => "noir_quizzes#noir_case", :as => "noir_case"

  resources :desktop_view

  match '/desktop_events', :to => 'desktop_view#desktop_events', :as => "desktop_events"
  match '/events_show/:id', :to => "desktop_view#events_show", :as => "events_show"
  match '/desktop_create_quest', :to => "desktop_view#desktop_create_quest", :as => "desktop_create_quest"
  match '/desktop_accept/event/:id', :to => "desktop_view#desktop_accept", :as => "desktop_accept"

  match '/feed_me', :to => "desktop_view#feed_me", :as => "feed_me"
  match '/desktop_ratings', :to => "desktop_view#desktop_ratings", :as => "desktop_ratings"
  match '/desktop_rating_appending', :to => "desktop_view#desktop_rating_appending", :as => "desktop_rating_appending"

  match '/meetings_index', :to => 'desktop_view#meetings_index', :as => "meetings_index"
  match '/desktop_focussed_new/:id', :to => "desktop_view#desktop_focussed_new", :as => "desktop_focussed_meeting"
  match '/meetings_new', :to => "desktop_view#meetings_new"
  match '/meetings_create', :to => "desktop_view#meetings_create", :as => "meetings_create"
  match '/meetings_show/:id', :to => "desktop_view#meetings_show", :as => "meetings_show"
  match '/meetings_accept/meeting/:id', :to => "desktop_view#meetings_accept", :as => "meetings_accept"
  match '/meetings_edit/:id', :to => "desktop_view#meetings_edit"
  match '/desktop_meeting_new_user', :to => "desktop_view#desktop_meeting_new_user", :as => "desktop_meeting_new_user"

  match '/messages_index', :to => 'desktop_view#messages_index', :as => "messages_index"
  match '/desktop_message_focussed_new/:id/(:message)/(:all)', :to => "desktop_view#desktop_message_focussed_new", :as => "desktop_focussed_message"
  match '/messages_new', :to => "desktop_view#messages_new", :as => "messages_new"
  match '/messages_create', :to => "desktop_view#messages_create", :as => "messages_create"
  match '/messages_show/:id', :to => "desktop_view#messages_show", :as => "messages_show"
  match '/messages_edit/:id', :to => "desktop_view#messages_edit"
  match '/messages_accept/meeting/:id', :to => "desktop_view#messages_accept", :as => "messages_accept"

  match '/delegates_search', :to => "desktop_view#delegates_search", :as => "delegates_search"
  match ':id/delegate_profile_index', :to => "desktop_view#delegate_profile_index", :as => "delegate_profile_index"
  match ':id/follow', :to => "desktop_view#desktop_following", :as => "desktop_following"
  match '/:id/desktop_edit_profile', :to => "desktop_view#desktop_edit_profile", :as => "desktop_edit_profile"
  match '/:id/desktop_update_profile', :to => "desktop_view#desktop_update_profile", :as => "desktop_update_profile"

  match '/desktop_graffiti', :to => "desktop_view#desktop_graffiti", :as => "desktop_graffiti"

  match '/desktop_assets_download', :to => "desktop_view#desktop_assets_download", :as => 'desktop_assets_download'

  match '/desktop_speaker', :to => "desktop_view#desktop_speaker", :as => 'desktop_speaker'

  match '/concierge_service_desktop', :to => "desktop_view#concierge_service_desktop", :as => "concierge_service_desktop"
  match '/order_services_desktop/:message', :to => "desktop_view#order_services_desktop", :as => "order_services_desktop"

``#----------Contact Us-------------#
  match '/contact_us_new', :to => "desktop_view#contact_us_new", :as => "contact_us_new"
  match '/contact_us_create', :to => "desktop_view#contact_us_create", :as => "contact_us_create"

``#----------Questionables-------------#
  match '/desktop_ask_question', :to => "desktop_view#desktop_ask_question", :as => "desktop_ask_question"

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/assets_download.html.erb
<%= content_for :page_title do %>
    Knowledge Center
<% end %>


<ul data-role="listview" data-theme="a" data-divider-theme="d" data-filter-placeholder="Search by events to download" data-split-icon='star' data-mini="true" data-filter="true">
  <% @assets_downloads.each do |e| %>
      <%if e.downloadable.url!='/avatars/original/missing.png'%>
          <% @event_id= e.track_id%>
          <li data-icon="file-text">
                <a target="_blank" class="index_styling" href="<%=e.downloadable.url%>" data-ajax=false>
                    <p><%= @event_name=Track.find(@event_id).name %></p>
                    <%= e.downloadable.original_filename %>
                    <%= hidden_field_tag e.id %>
                </a>
          </li>
      <% end %>
  <% end %>
</ul>


<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41279198-1', '127.0.0.1:3000');
    ga('send', 'pageview');

</script>

app/views/home/graffiti.html.erb
<style type="text/css">
    a, a:visited {
        color: black;
        text-decoration: none;
    }
</style>

<%= content_for :page_title do %>
    Graffiti
<% end %>

<%= content_for :head do %>
    <script type="text/javascript">

        function create_post() {

            var prev_status = $('#status_here').html();
            var create_at = "<%= @post.created_at unless @post.blank? %>";
            var data = {user_id:[], comment:[]}
            data["user_id"].push('<%= @user.id %>');
            data["comment"].push($('#comment').val());
            $.ajax({
                url:"<%= update_status_path %>",
                type:"post",
                data:JSON.stringify(data),
                contentType:"application/json",
                success:function (data) {

                    $('#status_here').html(data);
                    $('#comment').val("")

                    if (prev_status != "") {
                        $('.odd').prepend('<div style="background: rgba(178,204,255,0.93); width:auto;padding-left:5px;padding-top:4px;padding-bottom:4px;border-radius:5px;font-weight: bold;color:#333333;font-size: 0.8em;border-radius: 5px 5px 0px 0px; "><%= current_user.name %> <span style="float:right;margin-right: 5px;font-size: 0.8em;font-weight: normal;color:#333333">' + create_at + '</span></div><table style="background: #e2eefa;width:100%;border-radius: 0px 0px 5px 5px; "><tr><td><% unless current_user.picture.blank? %><%= image_tag(current_user.picture) %><% end %></td><td><p style="margin-left: 5px;margin-bottom: 5px;margin-top: 5px;font-size: 0.8em;color:#333333">' + prev_status + '</p></td></tr></table></div><br>');
                    }
                    $('[type="submit"]').button('disable');
                }
            });
        }


        $(function () {

            $('[type="submit"]').button('disable');
            $(function () {
                $('[type="submit"]').button('disable');
                $('#comment').focus(function () {
                    $('[type="submit"]').button('enable');
                    if (( $('#comment')).length > 0) {

                    } else {
                        $('[type="submit"]').button('disable');

                    }
                });

            });

            $('#comment').blur(function () {
                if ($(this).val().length <= 0) {
                    $('[type="submit"]').button('disable');
                }
                else {
                    $('[type="submit"]').button('enable');
                }
            });

        });


    </script>
<% end %>

<%= content_for :page_menu do %>

<% end %>






<div id="status_here" class="status" style="font-size: 0.8em;"><%= @post.name unless @post.blank? %></div>

<div id="text">
  <%= text_area_tag :comment, "", :placeholder => "Pen down your thoughts",:style =>"font-size: 0.8em;"  %>
</div>

<div id="stat_button">
  <%= submit_tag "Post it now!", :'data-role' => "button", :'data-theme' => "a", :onclick => "create_post();",:'data-mini' => "true" %>
</div>

<br>
<hr>

<% if !@upcoming_meetings.blank? %>
    <% @upcoming_meetings.each do |meeting| %>
        <div class="fbinfobox1">
          <div style="background: rgba(46,64,27,0.97); width:100%;padding-left:5px;padding-top:4px;padding-bottom:4px;border-radius:5px;font-weight: normal;">
            <%= ((meeting.meeters.select { |m| m.status }.map { |m| m.user.name } << meeting.user.name).delete_if { |n| n==current_user.name }).join(", ") %>

            <span style="float:right;margin-right: 5px;font-size: 0.7em;font-weight: normal;margin-top: 4px;"><%= meeting.start_time %>
              hrs on <%= meeting.start_time.strftime("%d %B") %></span>
          </div>
          <h3 style="margin-left: 5px;margin-bottom: 5px;margin-top: 5px;font-size: 0.8em;"><%= meeting.name %> @ <%= Location.find(meeting.location).name %></h3>
        </div>
    <% end %>
<% end %>


<% if !@upcoming_events.blank? %>
    <% @upcoming_events.each do |event| %>
        <div class="fbinfobox1">
          <div style="background: rgba(46,64,27,0.97); width:100%;padding-left:5px;padding-top:4px;padding-bottom:4px;border-radius:5px;font-weight: normal;">
            <%= event.name %>
            <span style="float:right;margin-right: 5px;font-size: 0.7em;font-weight: normal;margin-top: 4px;"><%= event.start %>
              hrs on <%= event.start.strftime("%d %B") %></span>
          </div>
          <h3 style="margin-left: 5px;margin-bottom: 5px;margin-top: 5px;font-size: 0.8em;"><%= event.description %></h3>
        </div>

    <% end %>
<% end %>

<br>

<% if !@notice_board.blank? %>
    <% @notice_board.each do |post| %>
        <div class="fbinfobox1">
          <div style="background: rgba(46,64,27,0.97); width:100%;padding-left:5px;padding-top:4px;padding-bottom:4px;border-radius:5px;font-weight: normal;">
            Organizer
            <span style="float:right;margin-right: 5px;font-size: 0.7em;font-weight: normal;margin-top: 4px;"><%= post.created_at %></span>
          </div>
          <table>
            <tr>
              <% unless post.user.picture.blank? %>
                  <td style="width:32px;max-width:32px;"><%= image_tag(post.user.picture) %></td>
              <% end %>
              <td><p style="margin-left: 5px;margin-bottom: 5px;margin-top: 5px;font-size: 0.8em;"><%= post.name %></p>
              </td>
            </tr>
          </table>
        </div>
    <% end %>
<% end %>

<br>

<% if !@followed.blank? %>
    <% @followed.each do |post| %>
        <% if !(post.user==current_user and post == @post) %>
            <div class="fbinfobox1">

              <div style="background: rgba(187,226,31,0.72); width:100%;padding-left:5px;padding-top:4px;padding-bottom:4px;border-radius:5px;font-weight: normal;">
                <%= link_to post.user.name.titlecase, user_profile_path(post.user), :style => "color:#333333;font-size:0.8em;font-weight:normal;" %>
                <span style="float:right;margin-right: 5px;font-size: 0.7em;font-weight: normal;margin-top: 4px;"><%= post.created_at %></span>
              </div>
              <table>
                <tr>
                  <% unless post.user.picture.blank? %>
                      <td style="width:32px;max-width:32px;"><%= image_tag(post.user.picture) %></td>
                  <% end %>
                  <td>
                    <p style="margin-left: 5px;margin-bottom: 5px;margin-top: 5px;font-size: 0.8em;"><%= post.name %></p>
                  </td>
                </tr>
              </table>
            </div>
        <% end %>
    <% end %>
<% end %>

<% if !@event_day_name.nil? %>
    <%= @event_day_name.name %>
<% end %>
<br>



<div class='odd'>
  <div data-role="collapsible" data-theme="a" data-collapsed="true" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d" data-inset="false" data-mini="true">
    <h3 style="font-size: 0.8em;">Event Wall</h3>
    <ul data-role="listview" data-theme="a" data-divider-theme="d">
      <% @graffiti.each do |post| %>
          <div class="fbinfobox1">
            <div style="background: rgba(178,204,255,0.93); width:100%;padding-left:5px;padding-top:4px;padding-bottom:4px;border-radius:5px;font-weight: normal;">
              <%= link_to post.user.name.titlecase, user_profile_path(post.user), :style => "color:#333333;font-size:0.8em;font-weight:normal;" %>
              <span style="float:right;margin-right: 5px;font-size: 0.8em;font-weight: normal;"><%= post.created_at %></span>
            </div>
            <% unless post.user.picture.blank? %>
                <p style="width:32px;max-width:32px;"><%= image_tag(post.user.picture) %></p>
            <% end %>
            <p style="margin-left: 5px;margin-bottom: 5px;margin-top: 5px;font-size: 0.8em;"><%= post.name %></p>
          </div>
      <% end %>
    </ul>
  </div>
</div>



<br>
<div id="posting" class="fbinfobox1" style="display: none;">
  <% if @post %>
      <% if @post.user!=current_user %>
          <div style="background: rgba(178,204,255,0.93); width:100%;padding-left:5px;padding-top:4px;padding-bottom:4px;border-radius:5px;font-weight: normal;">
            <span style="color:#333333;font-size:0.8em;font-weight:normal;"><%= @post.user.name.titlecase %></span>
            <span style="float:right;margin-right: 5px;font-size: 0.7em;font-weight: normal;margin-top: 4px;"><%= @post.created_at %></span>
          </div>
          <table>
            <tr>
              <% unless @post.user.picture.blank? %>
                  <td style="width:32px;max-width:32px;"><%= image_tag(@post.user.picture) %></td>
              <% end %>
              <td><p style="margin-left: 5px;margin-bottom: 5px;margin-top: 5px;font-size: 0.8em;"><%= post.name %></p>
              </td>
            </tr>
          </table>
      <% end %>
  <% end %>
</div>



<br>



<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41279198-1', '127.0.0.1:3000');
    ga('send', 'pageview');

</script>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= content_for :page_title do %>
      Procialize
  <% end %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag "responsiveslides" %>
  <%= javascript_include_tag "responsiveslides.min" %>



  <style type="text/css">
      .img_style {
          max-height: 200px;

      }

  </style>

  <style type="text/css">
      body {
          background-size: 100% 100%;
      }

      .ui-page {
          background: transparent;
      }

      .ui-content {
          background: transparent;
      }

      /*table, td, th*/

        /*td {*/
          /*text-align: left;*/
      /*}*/

  </style>




  <script>

      $(function () {
          $("#slider1").responsiveSlides({
              auto:true, // Boolean: Animate automatically, true or false
              speed:1500, // Integer: Speed of the transition, in milliseconds
              timeout:7000, // Integer: Time between slide transitions, in milliseconds
              random:true, // Boolean: Randomize the order of the slides, true or false
              pause:false, // Boolean: Pause on hover, true or false
              pauseControls:true, // Boolean: Pause when hovering controls, true or false
              maxwidth:"", // Integer: Max-width of the slideshow, in pixels
              navContainer:"", // Selector: Where controls should be appended to, default is after the 'ul'
              manualControls:"", // Selector: Declare custom pager navigation
              namespace:"rslides" // String: Change the default namespace used
          });


      });
  </script>
</head>
<body>


<div id="wrapper" style="height: 200px;">
  <ul class="rslides" id="slider1">
    <li><a href="http://www.isb.edu/solstice" target="_blank"><%= image_tag HomePageLogo.first.image_one.url, :class => "img_style" rescue"" %></a></li>
    <li><a href="http://www.isb.edu/solstice" target="_blank"><%= image_tag HomePageLogo.first.image_two.url, :class => "img_style" rescue"" %></a></li>
    <li><a href="http://www.isb.edu/solstice" target="_blank"><%= image_tag HomePageLogo.first.image_three.url, :class => "img_style" rescue"" %></a></li>
    <li><a href="http://www.isb.edu/solstice" target="_blank"><%= image_tag HomePageLogo.first.image_four.url, :class => "img_style"  rescue"" %></a></li>
    <li><a href="http://www.isb.edu/solstice" target="_blank"><%= image_tag HomePageLogo.first.image_five.url, :class => "img_style" rescue"" %></a></li>
    <li><a href="http://explore.calvinklein.com/en_US/explore" target="_blank"><%= image_tag HomePageLogo.first.image_six.url, :class => "img_style" rescue"" %></a></li>
    <li><a href="http://www.ethoswatches.com" target="_blank"><%= image_tag HomePageLogo.first.image_seven.url, :class => "img_style" rescue"" %></a></li>
    <li><a href="http://www.ethoswatches.com" target="_blank"><%= image_tag HomePageLogo.first.image_eight.url, :class => "img_style" rescue"" %></a></li>
    <li><a href="/noir_quizzes"><%= image_tag HomePageLogo.first.image_nine.url, :class => "img_style" rescue"" %></a></li>
    <!--<li><%#= image_tag HomePageLogo.first.image_seven.url, :class => "img_style" rescue"" %></li>-->
    <!--<li><%#= image_tag HomePageLogo.first.image_eight.url, :class => "img_style" rescue"" %></li>-->
    <!--<li><%#= image_tag HomePageLogo.first.image_nine.url, :class => "img_style" rescue"" %></li>-->
    <!--<li><%#= image_tag HomePageLogo.first.image_ten.url, :class => "img_style" rescue"" %></li>-->
    <!--<li><%#= image_tag HomePageLogo.first.event_image.url, :class => "img_style" rescue"" %></li>-->
    <!--<li><%#= image_tag HomePageLogo.first.conference_image.url, :class => "img_style" rescue"" %></li>-->
    <!--<li><%#= image_tag HomePageLogo.first.sponsor_image.url, :class => "img_style" rescue"" %></li>-->

    <% @survey_q= SurveyQuestion.all %>
    <% @survey_q.each do |s| %>
        <div id="surveys"  style="font-size: 1em;padding: 7px;">
          <li class="img_style" id="<%= s.id %>"><%= s.quest %>
            <br>
            <table cellpadding="3">
              <tr>
                <td style="vertical-align:top;"><%= s.option_a %></td>
                <td></td>
                <td></td>
                <td  style="vertical-align:middle;width:2em"><%= radio_button_tag "survey_options", "1", true, :class => "color_input", :style => "height:1em;width:1.5em;" %></td>
              </tr>
              <br>
              <tr>
                <td style="vertical-align:top;"><%= s.option_b %></td>
                <td></td>
                <td></td>
                <td  style="vertical-align:middle;width:2em;"><%= radio_button_tag "survey_options", "2", true, :class => "color_input", :style => "height:1em;width:1.5em;" %></td>
              </tr>
              <% if !s.option_c.blank? %>
                  <tr>
                    <td style="vertical-align:top;"><%= s.option_c %></td>
                    <td></td>
                    <td></td>
                    <td  style="vertical-align:middle;width:2em;"><%= radio_button_tag "survey_options", "3", true, :class => "color_input", :style => "height:1em;width:1.5em;" %></td>
                  </tr>
              <% end %>

              <% if !s.option_d.blank? %>
                  <tr>
                    <td style="vertical-align:top;"><%= s.option_d %></td>
                    <td></td>
                    <td></td>
                    <td  style="vertical-align:middle;width:2em;"><%= radio_button_tag "survey_options", "4", true, :class => "color_input", :style => "height:1em;width:1.5em;" %></td>
                  </tr>
              <% end %>
            </table>
          </li>
        </div>
    <% end %>
  </ul>



  <script type="text/javascript">
      $(function () {

          $("input[name=survey_options]").click(function () {
              var a = $(this).parent().parent().parent().parent().parent().parent().attr('id');
              var value = $(this).val();
              var data = { user_id:[], survey_question_id:[], ans:[]}
              data["user_id"].push('<%= current_user.id%>');
              data["survey_question_id"].push(a);
              data["ans"].push(value);
              $.ajax({
                  url:"<%= survey_storing_path %>",
                  type:"post",
                  data:JSON.stringify(data),
                  contentType:"application/json",
                  success:function (data) {
                      <%= add_gritter("Thank you for your response", :title => "Success",:image => :success,:time => 1000  ) %>
                  }
              });

          });

      });

  </script>
</div>

<div>

  <!--<a class="index_styling" href="/speaker" data-ajax=false data-role="button" data-icon="microphone" data-mini="true">Speakers</a>-->
  <a class="index_styling" href="/search/search" data-ajax=false data-role="button" data-icon="group" data-mini="true">Alumni</a>
  <!--<a class="index_styling" href="/ask_question" data-ajax=false data-role="button" data-icon="question" data-mini="true">Questions</a>-->
  <a class="index_styling" href="/graffiti" data-ajax=false data-role="button" data-icon="comment" data-mini="true">Status Updates</a>
  <a class="index_styling" href="/assets_download" data-ajax=false data-role="button" data-icon="download-alt" data-mini="true">Downloadables</a>
  <a class="index_styling" href="/ratings" data-ajax=false data-role="button" data-icon="exchange" data-mini="true">Feedback</a>
  <!--<a class="index_styling" href="/concierge_service" data-ajax=false data-role="button" data-icon="coffee" data-mini="true">Concierge</a>-->
  <!--<a class="index_styling" href="/index" data-ajax=false data-role="button" data-icon="tags" data-mini="true">Exhibitor</a>-->
  <a class="index_styling" href="/contacts/new" data-ajax=false data-role="button" data-icon="phone" data-mini="true">Contact
    Us</a>



</div>


</body>
</html>